### ISSUE TITLE
Feature Request:  Add Items to Vanilla D2

### ISSUE THREAD

**Issue by CodyFagley** [BetweenWalls/portal#5]
`Path of Diablo` offers the option of planning out a character's item build in addition to its skills.  This is a feature that all other apps whether web-based or mobile lack, but this is hands-down the closest to accomplishing that goal.  

I may get around to adding this to the Vanilla D2, but it would be good for someone to add it, regardless.  With D2: Resurrected coming out soon, this will be in demand -- Let's add it to "Portal".

**Comment by BetweenWalls** [comment]
I've done some of the work for this (setting up item info for vanilla unique/set/runeword items) but there is a major issue with code organization due to the feature-creep of this project, which has made fundamental changes like this unappealing to work on. The funny thing is that it probably wouldn't take many lines to get equipment working for vanilla in a rudimentary way - it's just that there are many tangential issues which would need to be found and accounted for.

**Comment by CodyFagley** [comment]
Yeah, I found that same thing when I gave it a crack.  With how the code is structured, it's a one-liner to show the item block on Vanilla.  But once that is done, it isn't _**quite**_ right, as you said in your comment.

**Comment by BetweenWalls** [comment]
Now that maxroll has both vanilla and pd2 planners with equipment and many other features, there's essentially no chance that I'll be adding vanilla items to portal.
